### ISSUE TITLE
FE/FEAT/Header 구현

### ISSUE THREAD

**Issue by hahagarden** [codestates-seb/seb44_pre_035#29]
## 요구사항 ID
ADD-I-001

## 요구사항
헤더 상단 네비게이션 구현

## 상세 요구사항
- 헤더 상단 네비게이션을 로그인과 비로그인을 구분하여 구현합니다.
- 스크롤을 해도 상단에 고정됩니다.

## TODO
- [x] 로그인
  - [x] 로고 이미지 (메인 페이지로 이동)
  - [x] 검색창 (제목/내용에 따른 검색)
  - [x] 로그아웃 버튼 (메인 페이지로 이동)

- [ ] 비로그인
  - [x] 버거 버튼
  - [x] 로고 이미지 (메인 페이지로 이동)
  - [x] 검색창 (제목/내용에 따른 검색)
  - [ ] 로그인 버튼 (로그인 페이지로 이동)
  - [x] 회원가입 버튼 (회원가입 페이지로 이동)

## 기타 사항
