### ISSUE TITLE
FE/FEAT/Header 기능 구현

### ISSUE THREAD

**Issue by hahagarden** [codestates-seb/seb44_pre_035#49]
## 요구사항 ID
ADD-I-001

## 요구사항
헤더 상단 네비게이션 기능 구현

## 상세 요구사항
- UI를 완성하고 백엔드 API가 구축되면 기능을 구현합니다.

## TODO
- [x] 로그인
  - [x] 로고 이미지 클릭시 메인 페이지로 이동
  - [x] 검색 (제목/내용에 따른 검색)

- [x] 비로그인
  - [x] 로고 이미지 클릭시 메인 페이지로 이동
  - [x] 검색 (제목/내용에 따른 검색)
  - [x] 로그인 버튼 클릭시 로그인 페이지로 이동
  - [x] 회원가입 버튼 클릭시 회원가입 페이지로 이동

## 기타 사항
